version: "3.8"
services:
  client:
    build: client
    stdin_open: true
    container_name: client
    image: sukruciris/mern_client:latest
    restart: always
    depends_on:
      - server
    ports:
      - 80:80

  server:
    container_name: server
    restart: always
    build: server
    depends_on:
      - mongo
    ports:
      - 8080:8080
    image: sukruciris/mern_server:latest

  mongo:
    container_name: mongo
    restart: always
    build: mongo
    ports:
      - 27017:27017
    image: sukruciris/mern_mongo:latest
