name: Docker Image CI-CD

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  runMultipleCommands:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - run: docker compose build
      - run: docker compose push
      - uses: appleboy/ssh-action@v1.0.0
        with:
          host: 2.tcp.eu.ngrok.io
          username: sukru
          password: sukru
          port: 18913
          script: |
            sudo git clone https://github.com/SUKRUCIRIS/MERN-Minikube-Ubuntu
            cd MERN-Minikube-Ubuntu
            sudo kubectl delete -R -f ./kubernetes-configs/ --ignore-not-found=true
            sudo kubectl create -R -f ./kubernetes-configs/
            cd ..
            sudo rm MERN-Minikube-Ubuntu
